### ISSUE TITLE
When initiating emoji commands, delete the users message that triggered it.

### ISSUE THREAD

**Issue by twist2k** [KhaosOrgSc/otterbot#3]
When a user initiates a command, for example !olove have the bot delete the users message triggering the command and still responding with the emoji. 

I will follow up with more info on how to accomplish this.

**Comment by KhaosOrgSc** [comment]
Done. 
https://github.com/KhaosOrgSc/otterbot/commit/efbc3496b2f2146dbc7c5312562dd20f11efc77e
